"""
CineOps AI - Production Planner Models
Structured Pydantic schemas for film production planning, scene grouping,
shooting schedules, resource allocation, and risk management.
"""

from typing import List, Optional
from pydantic import BaseModel, Field
from src.models.screenplay import ProductionRisk


class SceneGroup(BaseModel):
    """Represents a logical grouping of scenes based on shared locations, characters, or conditions."""
    group_id: str = Field(..., description="Unique grouping identifier, e.g. 'GRP-01'")
    group_name: str = Field(..., description="Descriptive title for the scene group")
    scene_numbers: List[str] = Field(default_factory=list, description="Scene numbers included in this group")
    location_name: str = Field(..., description="Primary location shared by this group")
    grouping_reason: str = Field(..., description="Explanation of why these scenes are grouped together")


class ShootingScheduleDay(BaseModel):
    """Represents a single day on the recommended shooting schedule."""
    day_number: int = Field(..., description="Day number in sequence (1, 2, 3...)")
    title: str = Field(..., description="Day title/focus, e.g. 'Alleyway Rain Sequences'")
    scene_numbers: List[str] = Field(default_factory=list, description="Scene numbers scheduled for this day")
    estimated_hours: float = Field(default=8.0, description="Estimated total shooting hours")
    location: str = Field(..., description="Location name for the shooting day")
    notes_and_rationale: str = Field(..., description="Shooting order rationale, lighting considerations, and crew notes")


class ResourceRequirement(BaseModel):
    """Represents a consolidated equipment, permit, crew, or prop requirement."""
    category: str = Field(..., description="Category (e.g. Equipment, Props, Permits, Crew, SFX, Safety)")
    item_name: str = Field(..., description="Name of required resource or equipment")
    required_for_scenes: List[str] = Field(default_factory=list, description="List of scene numbers requiring this resource")
    specification_details: Optional[str] = Field(default=None, description="Technical specs or vendor requirements")


class ResearchReference(BaseModel):
    """Reference to external research gathered via Parallel Search API."""
    topic: str = Field(..., description="Research topic or query intent")
    title: str = Field(..., description="Title of reference webpage or document")
    url: str = Field(..., description="URL of reference source")
    key_insight: str = Field(..., description="Key actionable insight incorporated into the production plan")


class ProductionPlan(BaseModel):
    """
    Top-level structured production plan generated by the Production Planner Agent.
    Synthesizes screenplay breakdowns and Parallel web research into an actionable production roadmap.
    """
    title: str = Field(default="CineOps Production Plan", description="Title of the production plan")
    overall_summary: str = Field(..., description="High-level executive summary of the production plan")
    total_estimated_days: int = Field(..., description="Total estimated principal photography days")
    scene_groupings: List[SceneGroup] = Field(default_factory=list, description="Groupings of scenes by location/time")
    shooting_schedule: List[ShootingScheduleDay] = Field(default_factory=list, description="Recommended day-by-day shooting schedule")
    location_recommendations: List[str] = Field(default_factory=list, description="Location scouting and setup recommendations")
    resource_requirements: List[ResourceRequirement] = Field(default_factory=list, description="Consolidated resource requirements")
    production_risks: List[ProductionRisk] = Field(default_factory=list, description="Consolidated production risks with severity and mitigations")
    research_references: List[ResearchReference] = Field(default_factory=list, description="Parallel web research sources referenced")
    strategic_reasoning: str = Field(..., description="Detailed explanation of strategic choices, scene sequencing, and cost/safety trade-offs")
