"""
CineOps AI - Overall Production Breakdown Model
"""

from typing import List, Optional
from pydantic import BaseModel, Field
from src.models.screenplay import SceneAnalysis


class ScreenplayProductionAnalysis(BaseModel):
    """
    Top-level structured result generated by the Screenplay Analyst Agent.
    Aggregates scene-by-scene breakdowns and high-level production metrics.
    """
    title: Optional[str] = Field(default="Untitled Screenplay", description="Title of the screenplay if detected")
    total_scenes: int = Field(..., description="Total count of analyzed scenes")
    scenes: List[SceneAnalysis] = Field(default_factory=list, description="Ordered list of structured scene breakdowns")
    all_characters: List[str] = Field(default_factory=list, description="Unique master list of all characters across the script")
    all_props: List[str] = Field(default_factory=list, description="Unique master list of all props featured")
    high_risk_scenes: List[str] = Field(default_factory=list, description="List of scene numbers flagged with HIGH or CRITICAL risks")
    summary: str = Field(..., description="Executive summary of production breakdown and operational considerations")
